# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons_Geral/program_icon64x64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 81))
        self.frame.setStyleSheet("background: #6C7F94")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(5, 15, 141, 51))
        self.pushButton.setStyleSheet("QPushButton{\n"
"border: 2px solid black;\n"
"border-radius: 23px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 2px solid white;\n"
"border-radius: 23px solid black;\n"
"background: #FAE8AA;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 15, 141, 51))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"border: 2px solid black;\n"
"border-radius: 23px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 2px solid white;\n"
"border-radius: 23px solid black;\n"
"background: #FAE8AA;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 80, 801, 521))
        self.stackedWidget.setStyleSheet("background: #BACCE0")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.op_1 = QtWidgets.QLineEdit(self.page)
        self.op_1.setGeometry(QtCore.QRect(15, 140, 311, 41))
        self.op_1.setStyleSheet("QLineEdit{\n"
"background: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"background: white;\n"
"border: 2px solid green;\n"
"border-radius: 20px;\n"
"}")
        self.op_1.setObjectName("op_1")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(670, 0, 128, 128))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Icons_Geral/register_icon128x128.png"))
        self.label.setObjectName("label")
        self.op_2 = QtWidgets.QLineEdit(self.page)
        self.op_2.setGeometry(QtCore.QRect(15, 190, 311, 41))
        self.op_2.setStyleSheet("QLineEdit{\n"
"background: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"background: white;\n"
"border: 2px solid green;\n"
"border-radius: 20px;\n"
"}")
        self.op_2.setObjectName("op_2")
        self.op_3 = QtWidgets.QLineEdit(self.page)
        self.op_3.setGeometry(QtCore.QRect(15, 240, 311, 41))
        self.op_3.setStyleSheet("QLineEdit{\n"
"background: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"background: white;\n"
"border: 2px solid green;\n"
"border-radius: 20px;\n"
"}")
        self.op_3.setObjectName("op_3")
        self.op_4 = QtWidgets.QLineEdit(self.page)
        self.op_4.setGeometry(QtCore.QRect(15, 290, 311, 41))
        self.op_4.setStyleSheet("QLineEdit{\n"
"background: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"background: white;\n"
"border: 2px solid green;\n"
"border-radius: 20px;\n"
"}")
        self.op_4.setObjectName("op_4")
        self.op_5 = QtWidgets.QLineEdit(self.page)
        self.op_5.setGeometry(QtCore.QRect(15, 340, 311, 41))
        self.op_5.setStyleSheet("QLineEdit{\n"
"background: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"background: white;\n"
"border: 2px solid green;\n"
"border-radius: 20px;\n"
"}")
        self.op_5.setObjectName("op_5")
        self.op_6 = QtWidgets.QLineEdit(self.page)
        self.op_6.setGeometry(QtCore.QRect(15, 390, 311, 41))
        self.op_6.setStyleSheet("QLineEdit{\n"
"background: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"background: white;\n"
"border: 2px solid green;\n"
"border-radius: 20px;\n"
"}")
        self.op_6.setObjectName("op_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.page)
        self.textBrowser.setGeometry(QtCore.QRect(380, 140, 401, 301))
        self.textBrowser.setObjectName("textBrowser")
        self.create_op = QtWidgets.QPushButton(self.page)
        self.create_op.setGeometry(QtCore.QRect(60, 450, 221, 61))
        self.create_op.setStyleSheet("QPushButton{\n"
"border: 2px solid black;\n"
"border-radius: 23px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 2px solid white;\n"
"border-radius: 23px solid black;\n"
"}")
        self.create_op.setObjectName("create_op")
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setGeometry(QtCore.QRect(670, 390, 128, 128))
        self.label_6.setStyleSheet("background: transparent;")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/Icons_Geral/control_128x128.png"))
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.op_save = QtWidgets.QPushButton(self.page_2)
        self.op_save.setGeometry(QtCore.QRect(160, 30, 171, 111))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.op_save.setFont(font)
        self.op_save.setStyleSheet("QPushButton{\n"
"background: #5A78AD;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background: #FAE8AA;\n"
"border: 2px solid white;\n"
"}")
        self.op_save.setText("")
        self.op_save.setObjectName("op_save")
        self.op_save_2 = QtWidgets.QPushButton(self.page_2)
        self.op_save_2.setGeometry(QtCore.QRect(370, 30, 171, 111))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.op_save_2.setFont(font)
        self.op_save_2.setStyleSheet("QPushButton{\n"
"background: #D1E1FF;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background: #FAE8AA;\n"
"border: 2px solid white;\n"
"}")
        self.op_save_2.setText("")
        self.op_save_2.setObjectName("op_save_2")
        self.op_save_3 = QtWidgets.QPushButton(self.page_2)
        self.op_save_3.setGeometry(QtCore.QRect(580, 30, 171, 111))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.op_save_3.setFont(font)
        self.op_save_3.setStyleSheet("QPushButton{\n"
"background: #B4CDFA;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background: #FAE8AA;\n"
"border: 2px solid white;\n"
"}")
        self.op_save_3.setText("")
        self.op_save_3.setIconSize(QtCore.QSize(64, 64))
        self.op_save_3.setObjectName("op_save_3")
        self.op_save_4 = QtWidgets.QPushButton(self.page_2)
        self.op_save_4.setGeometry(QtCore.QRect(160, 180, 171, 111))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.op_save_4.setFont(font)
        self.op_save_4.setStyleSheet("QPushButton{\n"
"background: #B5AFA2;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background: #FAE8AA;\n"
"border: 2px solid white;\n"
"}")
        self.op_save_4.setText("")
        self.op_save_4.setObjectName("op_save_4")
        self.op_save_5 = QtWidgets.QPushButton(self.page_2)
        self.op_save_5.setGeometry(QtCore.QRect(370, 180, 171, 111))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.op_save_5.setFont(font)
        self.op_save_5.setStyleSheet("QPushButton{\n"
"background: #FAE1AA;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background: #FAE8AA;\n"
"border: 2px solid white;\n"
"}")
        self.op_save_5.setText("")
        self.op_save_5.setObjectName("op_save_5")
        self.op_save_6 = QtWidgets.QPushButton(self.page_2)
        self.op_save_6.setGeometry(QtCore.QRect(580, 180, 171, 111))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.op_save_6.setFont(font)
        self.op_save_6.setStyleSheet("QPushButton{\n"
"background: #AD9B5A;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background: #FAE8AA;\n"
"border: 2px solid white;\n"
"}")
        self.op_save_6.setText("")
        self.op_save_6.setObjectName("op_save_6")
        self.frame_2 = QtWidgets.QFrame(self.page_2)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 141, 501))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.op_selecionada1 = QtWidgets.QLabel(self.frame_2)
        self.op_selecionada1.setGeometry(QtCore.QRect(0, 70, 0, 41))
        self.op_selecionada1.setStyleSheet("background: #5A78AD;")
        self.op_selecionada1.setText("")
        self.op_selecionada1.setAlignment(QtCore.Qt.AlignCenter)
        self.op_selecionada1.setObjectName("op_selecionada1")
        self.op_selecionada2 = QtWidgets.QLabel(self.frame_2)
        self.op_selecionada2.setGeometry(QtCore.QRect(0, 120, 0, 41))
        self.op_selecionada2.setStyleSheet("background: #D1E1FF;")
        self.op_selecionada2.setText("")
        self.op_selecionada2.setAlignment(QtCore.Qt.AlignCenter)
        self.op_selecionada2.setObjectName("op_selecionada2")
        self.op_selecionada3 = QtWidgets.QLabel(self.frame_2)
        self.op_selecionada3.setGeometry(QtCore.QRect(0, 170, 0, 41))
        self.op_selecionada3.setStyleSheet("background: #B4CDFA;")
        self.op_selecionada3.setText("")
        self.op_selecionada3.setAlignment(QtCore.Qt.AlignCenter)
        self.op_selecionada3.setObjectName("op_selecionada3")
        self.op_selecionada4 = QtWidgets.QLabel(self.frame_2)
        self.op_selecionada4.setGeometry(QtCore.QRect(0, 220, 0, 41))
        self.op_selecionada4.setStyleSheet("background: #B5AFA2;")
        self.op_selecionada4.setText("")
        self.op_selecionada4.setAlignment(QtCore.Qt.AlignCenter)
        self.op_selecionada4.setObjectName("op_selecionada4")
        self.op_selecionada5 = QtWidgets.QLabel(self.frame_2)
        self.op_selecionada5.setGeometry(QtCore.QRect(0, 270, 0, 41))
        self.op_selecionada5.setStyleSheet("background: #FAE1AA;")
        self.op_selecionada5.setText("")
        self.op_selecionada5.setAlignment(QtCore.Qt.AlignCenter)
        self.op_selecionada5.setObjectName("op_selecionada5")
        self.op_selecionada6 = QtWidgets.QLabel(self.frame_2)
        self.op_selecionada6.setGeometry(QtCore.QRect(0, 320, 0, 41))
        self.op_selecionada6.setStyleSheet("background: #AD9B5A;")
        self.op_selecionada6.setText("")
        self.op_selecionada6.setAlignment(QtCore.Qt.AlignCenter)
        self.op_selecionada6.setObjectName("op_selecionada6")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background: #473B26;\n"
"color: white;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(430, 120, 64, 64))
        self.label_2.setStyleSheet("background: transparent")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Icons_Geral/Icon_foguete_64x64.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(670, 390, 129, 128))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/Icons_Geral/control_128x128.png"))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setGeometry(QtCore.QRect(640, 120, 64, 64))
        self.label_5.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("background: transparent")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/Icons_Geral/ship_64x64.png"))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setGeometry(QtCore.QRect(210, 120, 64, 64))
        self.label_7.setStyleSheet("background: transparent")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/Icons_Geral/horse_64x64.png"))
        self.label_7.setObjectName("label_7")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.page_2)
        self.textBrowser_2.setGeometry(QtCore.QRect(150, 310, 391, 192))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tecnologia Assistiva"))
        self.pushButton.setText(_translate("MainWindow", "GERENCIAR OPÇÕES"))
        self.pushButton_2.setText(_translate("MainWindow", "INICIO"))
        self.op_1.setPlaceholderText(_translate("MainWindow", "OPÇÃO 01"))
        self.op_2.setPlaceholderText(_translate("MainWindow", "OPÇÃO 02"))
        self.op_3.setPlaceholderText(_translate("MainWindow", "OPÇÃO 03"))
        self.op_4.setPlaceholderText(_translate("MainWindow", "OPÇÃO 04"))
        self.op_5.setPlaceholderText(_translate("MainWindow", "OPÇÃO 05"))
        self.op_6.setPlaceholderText(_translate("MainWindow", "OPÇÃO 06"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ff0000;\">COMO FUNCIONA</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#000000;\">1. Na versão 2.0 do programa, utilizamos 6 opções customizáveis;</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#000000;\">2. Através de um arduino e programação em Python, nosso sistema</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#000000;\">reconhece e seleciona as opções por conta própria, dependendo apenas do usuário para decidir se ela será selecionada ou não;</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#000000;\">3. Após definir as opções, elas ficam salva no sistema até trocar novamente;</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#000000;\">4. Essa área de gerênciamento de opções é distinada apenas ao responsável.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ff0000;\">DICA: PROCURE SEMPRE UTILIZAR DE PALAVRAS PEQUENAS E SIMPLES.</span></p></body></html>"))
        self.create_op.setText(_translate("MainWindow", "INICIAR"))
        self.label_4.setText(_translate("MainWindow", "OPÇÕES"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">INSTRUÇÕES</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#000000;\">1. Click: O Click é realizado quando o sensor atinge o valor </span><span style=\" font-size:12pt; text-decoration: underline; color:#000000;\">500</span><span style=\" font-size:12pt; color:#000000;\"> .</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#000000;\">2. Parar: O Programa é finalizado após o sensor atingir qualquer valor acima de </span><span style=\" font-size:12pt; text-decoration: underline; color:#000000;\">1000</span><span style=\" font-size:12pt; color:#000000;\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#000000;\">3. A Esquerda do programa é onde ficará localizado as opções selecionadas.</span></p></body></html>"))
import icons_rc
