# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(407, 532)
        MainWindow.setMinimumSize(QtCore.QSize(407, 532))
        MainWindow.setMaximumSize(QtCore.QSize(407, 532))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 411, 80))
        self.frame.setStyleSheet("QFrame{\n"
"background: #6363B8;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.player_button = QtWidgets.QPushButton(self.frame)
        self.player_button.setGeometry(QtCore.QRect(100, 10, 75, 61))
        self.player_button.setStyleSheet("QPushButton{\n"
"border: 2px solid black;\n"
"border-radius: 13px;\n"
"color: white\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 2px solid white;\n"
"border-radius: 13px;\n"
"}")
        self.player_button.setObjectName("player_button")
        self.download_button = QtWidgets.QPushButton(self.frame)
        self.download_button.setGeometry(QtCore.QRect(10, 10, 75, 61))
        self.download_button.setStyleSheet("QPushButton{\n"
"border: 2px solid black;\n"
"border-radius: 13px;\n"
"color: white\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 2px solid white;\n"
"border-radius: 13px;\n"
"}")
        self.download_button.setObjectName("download_button")
        self.close = QtWidgets.QPushButton(self.frame)
        self.close.setGeometry(QtCore.QRect(320, 10, 75, 61))
        self.close.setStyleSheet("QPushButton{\n"
"border: 2px solid black;\n"
"border-radius: 13px;\n"
"color: white\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 2px solid white;\n"
"border-radius: 13px;\n"
"}")
        self.close.setObjectName("close")
        self.img_player = QtWidgets.QFrame(self.centralwidget)
        self.img_player.setGeometry(QtCore.QRect(0, 80, 411, 231))
        self.img_player.setStyleSheet("")
        self.img_player.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img_player.setFrameShadow(QtWidgets.QFrame.Raised)
        self.img_player.setObjectName("img_player")
        self.stackedWidget = QtWidgets.QStackedWidget(self.img_player)
        self.stackedWidget.setGeometry(QtCore.QRect(-1, -1, 411, 231))
        self.stackedWidget.setObjectName("stackedWidget")
        self.download_page = QtWidgets.QWidget()
        self.download_page.setObjectName("download_page")
        self.addURL = QtWidgets.QLineEdit(self.download_page)
        self.addURL.setGeometry(QtCore.QRect(30, 40, 351, 41))
        self.addURL.setStyleSheet("QLineEdit{\n"
"border: 2px solid black;\n"
"border-radius: 13px;\n"
"}\n"
"\n"
"QLineEdit:Hover{\n"
"border: 2px solid green;\n"
"border-radius: 13px;\n"
"}\n"
"")
        self.addURL.setObjectName("addURL")
        self.download_button_2 = QtWidgets.QPushButton(self.download_page)
        self.download_button_2.setGeometry(QtCore.QRect(20, 160, 371, 61))
        self.download_button_2.setStyleSheet("QPushButton{\n"
"border: 2px solid black;\n"
"border-radius: 13px;\n"
"color: black;\n"
"background: #AC75FF;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"border: 2px solid white;\n"
"border-radius: 13px;\n"
"}")
        self.download_button_2.setObjectName("download_button_2")
        self.stackedWidget.addWidget(self.download_page)
        self.player_page = QtWidgets.QWidget()
        self.player_page.setObjectName("player_page")
        self.stackedWidget.addWidget(self.player_page)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 310, 411, 181))
        self.frame_2.setStyleSheet("background: #A6A6FF")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 490, 411, 41))
        self.frame_3.setStyleSheet("background: #ADAB9E")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(0, 10, 411, 21))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.frame.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Top Menu</p></body></html>"))
        self.player_button.setText(_translate("MainWindow", "Player"))
        self.download_button.setText(_translate("MainWindow", "Download"))
        self.close.setText(_translate("MainWindow", "Exit"))
        self.addURL.setPlaceholderText(_translate("MainWindow", "URL"))
        self.download_button_2.setText(_translate("MainWindow", "Download"))
        self.label.setText(_translate("MainWindow", "By: xand.douglass@gmail.com"))
