# Generated by Django 3.2.6 on 2021-08-17 15:08

import core.models
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('fone', models.CharField(blank=True, default='Não possui', max_length=15, verbose_name='Telefone')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('funcao', models.CharField(blank=True, default='Não possui', max_length=20, verbose_name='Função')),
                ('identificacao', models.CharField(max_length=20, unique=True, verbose_name='Identificação')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Membro da equipe')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', core.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Titulo da Noticia')),
                ('descricao', models.TextField(help_text='Máximo de 500 caracteres', max_length=500, verbose_name='Descrição')),
                ('texto', models.TextField(verbose_name='Parágrafo 01')),
                ('texto_2', models.TextField(blank=True, default=None, verbose_name='Parágrafo 02')),
                ('texto_3', models.TextField(blank=True, default=None, verbose_name='Parágrafo 03')),
                ('imagem', stdimage.models.StdImageField(upload_to='news', verbose_name='Imagem')),
                ('imagem_2', stdimage.models.StdImageField(blank=True, default=None, upload_to='news', verbose_name='Galeria 01')),
                ('imagem_3', stdimage.models.StdImageField(blank=True, default=None, upload_to='news', verbose_name='Galeria 02')),
                ('imagem_4', stdimage.models.StdImageField(blank=True, default=None, upload_to='news', verbose_name='Galeria 03')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Porturgue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(blank=True, default='Português', max_length=100, verbose_name='Matéria')),
                ('matricula', models.CharField(max_length=100, unique=True, verbose_name='Confirmar Matrícula')),
                ('nota01', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, verbose_name='Nota 01')),
                ('nota02', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, verbose_name='Nota 02')),
                ('nota03', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, verbose_name='Nota 03')),
                ('nota04', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, verbose_name='Nota 04')),
                ('nota05', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, verbose_name='Nota 05')),
                ('nota06', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, verbose_name='Nota 06')),
                ('media', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, verbose_name='Média')),
                ('faltas', models.CharField(blank=True, default='0', max_length=100, verbose_name='Número de Faltas')),
                ('status', models.CharField(blank=True, default='Em Progresso', max_length=100, verbose_name='Situação do Aluno')),
                ('observacao', models.TextField(blank=True, default='Nenhuma observação adicionada', verbose_name='Observação do Professor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome_da_turma', models.CharField(max_length=100, unique=True, verbose_name='Turma')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Matematic',
            fields=[
                ('porturgue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.porturgue')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.porturgue',),
        ),
        migrations.CreateModel(
            name='AlunoCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Aluno')),
                ('matricula', models.CharField(max_length=100, unique=True, verbose_name='Matrícula')),
                ('nascimento', models.CharField(default='XX/XX/XXXX', max_length=15, verbose_name='Data de Nascimento')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
                ('dados', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('disciplina_1', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplina01', to='core.porturgue')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turma')),
                ('disciplina_2', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplina02', to='core.matematic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
