# Generated by Django 3.2.6 on 2021-08-18 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biologia',
            fields=[
                ('porturgue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.porturgue')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.porturgue',),
        ),
        migrations.CreateModel(
            name='Fisica',
            fields=[
                ('porturgue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.porturgue')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.porturgue',),
        ),
        migrations.CreateModel(
            name='Geografia',
            fields=[
                ('porturgue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.porturgue')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.porturgue',),
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('porturgue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.porturgue')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.porturgue',),
        ),
        migrations.CreateModel(
            name='Quimica',
            fields=[
                ('porturgue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.porturgue')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.porturgue',),
        ),
        migrations.AddField(
            model_name='alunocadastro',
            name='disciplina_3',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplina03', to='core.matematic'),
        ),
        migrations.AddField(
            model_name='alunocadastro',
            name='disciplina_4',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplina04', to='core.matematic'),
        ),
        migrations.AddField(
            model_name='alunocadastro',
            name='disciplina_5',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplina05', to='core.matematic'),
        ),
        migrations.AddField(
            model_name='alunocadastro',
            name='disciplina_6',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplina06', to='core.matematic'),
        ),
        migrations.AddField(
            model_name='alunocadastro',
            name='disciplina_7',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplina07', to='core.matematic'),
        ),
        migrations.AddField(
            model_name='alunocadastro',
            name='disciplina_8',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplina08', to='core.matematic'),
        ),
    ]
