# Generated by Django 3.2.6 on 2021-08-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210818_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunocadastro',
            name='disciplina_3',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplina03', to='core.geografia'),
        ),
        migrations.AlterField(
            model_name='alunocadastro',
            name='disciplina_4',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplina04', to='core.historia'),
        ),
        migrations.AlterField(
            model_name='alunocadastro',
            name='disciplina_5',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplina05', to='core.biologia'),
        ),
        migrations.AlterField(
            model_name='alunocadastro',
            name='disciplina_6',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplina06', to='core.fisica'),
        ),
        migrations.AlterField(
            model_name='alunocadastro',
            name='disciplina_7',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplina07', to='core.quimica'),
        ),
    ]
