# Generated by Django 3.2.6 on 2021-08-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210819_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porturgue',
            name='matricula',
            field=models.CharField(max_length=100, verbose_name='Confirmar Matrícula'),
        ),
    ]
