# Generated by Django 3.2.6 on 2021-08-26 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_porturgue_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='texto_2',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='texto_3',
        ),
    ]
