# Generated by Django 3.2.6 on 2021-08-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210826_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='descricao',
            field=models.TextField(help_text='Máximo de 1000 caracteres', max_length=1000, verbose_name='Descrição'),
        ),
    ]
